### ISSUE TITLE
crash on tax update changed on LI update

### ISSUE THREAD

**Issue by 9ae** [9ae/Bowls#62]
1. frantically input tax amount
2. then the bowl selector button shows
3. then input more again
4. press enter and app crashes.

05-28 22:36:02.855: E/AndroidRuntime(27100):    at me.valour.bowls.Bill.itemUpdate(Bill.java:292)
05-28 22:36:02.855: E/AndroidRuntime(27100):    at me.valour.bowls.TableActivity.updateItemPrice(TableActivity.java:177)
05-28 22:36:02.855: E/AndroidRuntime(27100):    at me.valour.bowls.TableActivity.numPadClose(TableActivity.java:485)
05-28 22:36:02.855: E/AndroidRuntime(27100):    at me.valour.bowls.NumberPadFragment$1.onClick(NumberPadFragment.java:123)

**Comment by 9ae** [comment]
BillFragment items not disabled.
